baseURL = ''
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
title = 'Pierrot fait la roue'
theme = 'pego'

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "Pierrot fait la roue"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Pierrot fait la roue"
