baseURL = ''
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
title = 'Atelier de Pierrot'
theme = 'pego'

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "Atelier de Pierrot"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Atelier de Pierrot"
